version: '3'
services:

  api-server:
      build: .
      image: hechuan73/config_manager
      restart: always
      ports:
        - 18898:18898
      networks:
        - my-network

networks:
    my-network:
      # driver: overlay
      driver: bridge

